### ISSUE TITLE
New DF-beta build, new (minor?) errors

### ISSUE THREAD

**Issue by ZINK-ZINK** [ItsJustMeChris/idTip-Community-Fork#11]
Seems like Blizz changed the tooltip code yet again. On Load I get these errors, but they don't seem to repeat in game or interfere with anything. The 3rd error is from Leatrix Plus, but it seems interconnected enough that it might be helpful. Blizzard really doesn't make things easy do they? lol

1x Interface/AddOns/idTip/clients/shared.lua:137: ItemRefTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@Interface/AddOns/idTip/clients/shared.lua"]:137: in main chunk

Locals:
(*temporary) = ItemRefTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:283
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetExistingSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 shoppingTooltips = <table> {
 }
 updateTooltipTimer = 0.200000
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:318
 OnDragStop = <function> defined @Interface/FrameXML/ItemRef.lua:729
 SetQuestLogCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 StatusBar = ItemRefTooltipStatusBar {
 }
 AddLineDataText = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:304
 SetVoidItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:943
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 TextRight1 = ItemRefTooltipTextRight1 {
 }
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:985
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetPossession = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetTradeTargetItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 OnEnter = <function> defined @Interface/FrameXML/ItemRef.lua:734
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 OnDragStart = <function> defined @Interface/FrameXML/ItemRef.lua:725
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 OnLeave = <function> defined @Interface/FrameXML/ItemRef.lua:738
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:224
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:273
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 ItemRefSetHyperlink = <function> defined @Interface/FrameXML/ItemRef.lua:745
 supportsDataRefresh = true
 SetLootRollItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:924
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tool

**Comment by ZINK-ZINK** [comment]
1x Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:3332: GameTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:3332: in function `?'
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:13929: in function <Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:13293>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:283
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetExistingSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:318
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 shoppingTooltips = <table> {
 }
 updateTooltipTimer = 0.200000
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:943
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 ItemTooltip = Frame {
 }
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:985
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 StatusBar = GameTooltipStatusBar {
 }
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 AddLineDataText = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:304
 SetVoidItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 TextRight1 = GameTooltipTextRight1 {
 }
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:224
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:273
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 supportsItemComparison = true
 supportsDataRefresh = true
 SetLootRollItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:924
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:916
 SetAction = <function> defined =[C]:-1
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:981
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:424
 SetInventoryItemByID = <function> defined @Interface/SharedXML/Tooltip/Toolti

**Comment by spaceturttle** [comment]
I'm also getting this along with a new window I haven't seen before
"idTip has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI"

idTip currently works on spells, but does not work on items

**Comment by ZINK-ZINK** [comment]
I haven't used this addon, but apparently it adds Talent and Profession Tooltips too. There might be some useful code ideas in there for you 

https://www.curseforge.com/wow/addons/talent-tree-tweaks

**Comment by ItsJustMeChris** [comment]
Addressed in https://github.com/ItsJustMeChris/idTip-Community-Fork/releases/tag/11.0.5
