### ISSUE TITLE
Request: Start using version numbers for updates on Curse

### ISSUE THREAD

**Issue by ZINK-ZINK** [ItsJustMeChris/idTip-Community-Fork#14]
This is a minor issue, but just seeing a list of "IdTip.zip" on curseforge is confusing. I understand keeping it simple up to now since you'd be at version eleventy-billion already, but now that things are stable it would be helpful to see the exact versions in the file listings going forward. 

Thanks again for taking over IdTip btw.

**Comment by ItsJustMeChris** [comment]
They will be now that the release automation spits them out with the version. Makes it easier for me to download and upload anyways 😅
