### ISSUE TITLE
reputation reward tooltip without numbers

### ISSUE THREAD

**Issue by yoshimo** [ItsJustMeChris/idTip-Community-Fork#26]
![grafik](https://user-images.githubusercontent.com/17909/202243224-6ca0c423-a7fe-467e-b040-49a17aca42f8.png)
This tooltip should have some kind of number, i guess it is a currency.

**Comment by ItsJustMeChris** [comment]
Added in https://github.com/ItsJustMeChris/idTip-Community-Fork/releases/tag/11.0.30
