### ISSUE TITLE
Error when hovering within achievements and TSM addon enabled

### ISSUE THREAD

**Issue by Caerdon** [ItsJustMeChris/idTip-Community-Fork#27]
Getting the following error when hovering over certain achievement criteria in the achievement frame and TSM and idTip are enabled:

Message: .../AddOns/idTip_CommunityFork/clients/dragonflight.lua:92: GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found
Time: Sat Nov 19 13:02:22 2022
Count: 2
Stack: .../AddOns/idTip_CommunityFork/clients/dragonflight.lua:92: GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua"]:769: in function <...Ons/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:725>
[string "=[C]"]: ?
[string "=[C]"]: in function `GetAchievementCriteriaInfo'
[string "@Interface/AddOns/idTip_CommunityFork/clients/dragonflight.lua"]:92: in function <.../AddOns/idTip_CommunityFork/clients/dragonflight.lua:86>

Locals: errMsg = ".../AddOns/idTip_CommunityFork/clients/dragonflight.lua:92: GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:525
 ErrorHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface/AddOns/WagoAnalytics/WagoAnalytics.lua:70
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:544
 num = 0
 SanitizeString = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:518
 AddonBlockedHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by ItsJustMeChris** [comment]
Okay I think I finally figured out what was going on with achievements, I think it had to do with blizzard using a framepool and the hooks that were being placed were 'caching' the index of the criteria it was created for instead of representing the actual current criteria that's being hovered over. I believe this should be fixed in the next release.
