### ISSUE TITLE
Deprecated global.

### ISSUE THREAD

**Issue by Tga123** [ItsJustMeChris/idTip-Community-Fork#29]
In .\clients\shared.lua:
```lua
(246  )     local petIndex = C_PetBattles.GetActivePet(LE_BATTLE_PET_ALLY)
(248  )       local id = select(1, C_PetBattles.GetAbilityInfo(LE_BATTLE_PET_ALLY, petIndex, self:GetID()))
```

LE_BATTLE_PET_ALLY be deprecated in 9.1.0, and removed in 10.0.

But C_PetBattles.GetActivePet() and C_PetBattles.GetAbilityInfo() not producing errors, just return incorrect values.

Now need use Enum.BattlePetOwner.Ally instead.

**Comment by ItsJustMeChris** [comment]
Changed in the next release ( https://github.com/ItsJustMeChris/idTip-Community-Fork/releases/tag/11.0.28 )
