### ISSUE TITLE
11.00.28 broke id's on compare items

### ISSUE THREAD

**Issue by cp1pro** [ItsJustMeChris/idTip-Community-Fork#31]
in 11.00.28 id's on compare items dont shown, its work on 00.27
![Screenshot_1338](https://user-images.githubusercontent.com/118368537/202930956-728d04c4-7fbf-4b05-a0f5-fdc7dc0ec966.png)

**Comment by ItsJustMeChris** [comment]
Fixed https://github.com/ItsJustMeChris/idTip-Community-Fork/releases/tag/11.0.29
