### ISSUE TITLE
Mouseovering nameplate debuff tooltip

### ISSUE THREAD

**Issue by lowpita** [ItsJustMeChris/idTip-Community-Fork#32]
Hey. Got this error after mouseovering a debuff from an enemy nameplate debuff which then turns into a friendly/neutral nameplate one. Seems to be related to what I commented here: https://github.com/frozn/TipTac/issues/132#issuecomment-1321391533

11x idTip_CommunityFork/core/shared.lua:101: calling 'GetName' on bad self (Usage: local name = self:GetName())
[string "=[C]"]: in function `GetName'
[string "@idTip_CommunityFork/core/shared.lua"]:101: in function `addLine'
[string "@idTip_CommunityFork/clients/dragonflight.lua"]:178: in function <idTip_CommunityFork/clients/dragonflight.lua:177>
[string "=[C]"]: ?

Locals:
(*temporary) = NamePlateTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 ttGradient = Texture {
 }
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBackdropColor = <function> defined @TipTac/ttCore.lua:1746
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:324
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextLeft1 = NamePlateTooltipTextLeft1 {
 }
 SetAzeritePower = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = NamePlateTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined =[C]:-1
 SetTotem = <function> defined @I

**Comment by lowpita** [comment]
Recorded a clip reproducing it: https://medal.tv/es/games/world-of-warcraft/clips/Jg0U0H47Ee6zj/d1337P41oOqh

**Comment by ItsJustMeChris** [comment]
Not able to reproduce it with tiptac, it seems like for some reason they're overriding `NamePlateTooltip` or something causing it to load it's GetName function as seen in the table of functions at [0] in your error report..
