### ISSUE TITLE
minor bug

### ISSUE THREAD

**Issue by cp1pro** [ItsJustMeChris/idTip-Community-Fork#34]
if we move cursor like in screenshot, tooltip does not hide, until we get new one
![Screenshot_1343](https://user-images.githubusercontent.com/118368537/203630201-064f18b1-e624-4bd0-8ca7-26b8f5bc6b4a.png)

**Comment by ItsJustMeChris** [comment]
Fixed in https://github.com/ItsJustMeChris/idTip-Community-Fork/releases/tag/11.0.30
