### ISSUE TITLE
Achievement Criteria IDs not shown for all criteria types

### ISSUE THREAD

**Issue by zarillion** [ItsJustMeChris/idTip-Community-Fork#36]
In my original patch for Dragonflight criteria tracking it handled all criteria types, not just the textual ones. That meant progress bars and sub-achievement criteria ids could also be displayed. That appears to be lost in the current release:

![image](https://user-images.githubusercontent.com/64381982/205398992-feff9113-4bab-413e-ae36-3290bc6f5823.png)

For example, the criteria ID for the race achievements like the one above is not shown.

**Comment by ItsJustMeChris** [comment]
I believe these are sub achievements and not criteria, but I can look into adding support for them eventually.

**Comment by kemayo** [comment]
Sub-achievements are just a criteria-type -- if type is 8, the assetID for the criteria will be an achievementID. The criteriaID for the line is still present. The main difference is that it's little sub-buttons that you can click to jump to the achievement, and they already have a tooltip set, so I'd guess that the reason the criteriaID isn't showing is just that it's a different function to hook into.

**Comment by ItsJustMeChris** [comment]
Yes these are not mini achievements, they're achievement 'Meta'

**Comment by ItsJustMeChris** [comment]
Added support for achievement meta in https://github.com/ItsJustMeChris/idTip-Community-Fork/releases/tag/11.0.31
