### ISSUE TITLE
Talents without ID on the 10.0 PTR (46112)

### ISSUE THREAD

**Issue by yoshimo** [ItsJustMeChris/idTip-Community-Fork#5]
![grafik](https://user-images.githubusercontent.com/17909/195991156-55edfc0d-9f97-49e2-954d-fa97ada4c57f.png)

This tooltip isn't covered

**Comment by ItsJustMeChris** [comment]
I'll have to look at PTR separately, but the functionality is still there on beta. 

https://i.imgur.com/7fFA9WG.png

**Comment by ItsJustMeChris** [comment]
These are fixed in my latest commit

**Comment by yoshimo** [comment]
Beta and PTR run on different builds for some reason, hopefully they don't diverge too much.

**Comment by yoshimo** [comment]
Seems solved for now , thanks
