### ISSUE TITLE
bugsack errors

### ISSUE THREAD

**Issue by romper008** [ItsJustMeChris/idTip-Community-Fork#50]
1) **15x idTip_CommunityFork/clients/dragonflight.lua:1 (null)**

2) **15x Interface\FrameXML\Bindings.xml:1 idTip_CommunityFork/clients/dragonflight.lua:1 (null)**

3) **15x idTip_CommunityFork/clients/dragonflight.lua:332: Usage: hooksecurefunc([table,] "function", hookfunc)**
[string "=[C]"]: in function `hooksecurefunc'
[string "@idTip_CommunityFork/clients/dragonflight.lua"]:332: in main chunk

Locals:
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML/ActionButton.lua:73
 ERR_OUT_OF_CHI = "Недостаточно энергии ци"
 DH_HAVOC_CORE_ABILITY_2 = "Мощная атака ближнего боя, расходующая гнев. Возмещает затраты гнева, если наносит критический урон."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Цветовое выделение названий объектов."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Скрыть художественные элементы панели"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 774
 SPELL_FAILED_CUSTOM_ERROR_71 = "Этот кутила хочет потанцевать с вами."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Нельзя создать больше ссылок для приглашение в это сообщество."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Сумки, являющиеся частью экипировки, не продаются и не покупаются."
 PVP_RANK_6_1 = "Капрал"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Отображение слева от правой панели команд 1 по умолчанию"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 371
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "Нет"
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Отображение справа от правой панели команд 4 по умолчанию"
 BINDING_NAME_NAMEPLATES = "Показать индикаторы врагов"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s не может войти. Подземелье временно заблокировано."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Здоровье"
 MAIL_LETTER_TOOLTIP = "Щелкните здесь, чтобы сделать
копию этого письма."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:927
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 MANA = "Мана"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML/FloatingChatFrame.lua:2388
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "Невозможно прошептать: "%s". Служба Blizzard может быть недоступна."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML/AutoComplete.lua:368
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d ч"
 ToggleEncounterJournal = <function> defined @FrameXML/UIParent.lua:1136
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Страх"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Атака ближнего боя, которая завершает серию."
 JoinSkirmish = <function> defined =[C]:-1
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Список покупок по умолчан

**Comment by Breakerzeus** [comment]
I would assume you update you addons via CurseForge? I also got that error for quite a while and fixed it recently. I think the issue was, that  CF somehow installed the 2022 version (all files are from 2022) and that causes this error (I guess because of some profession things). But if you look at your installed addons in CF now then you won't find IdTip installed. I think they had an issue a while ago or something like that. But if you just install the latest version (need to search for the addon) again, then the errors are disappearing.

**Comment by romper008** [comment]
> I would assume you update you addons via CurseForge? I also got that error for quite a while and fixed it recently. I think the issue was, that CF somehow installed the 2022 version (all files are from 2022) and that causes this error (I guess because of some profession things). But if you look at your installed addons in CF now then you won't find IdTip installed. I think they had an issue a while ago or something like that. But if you just install the latest version (need to search for the addon) again, then the errors are disappearing.

yea, you're right, thanks
